### PR TITLE
Fix bug in patch file

### PR DESCRIPTION
**Pull request by kordejong**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kordejong** [comment]
Now the patch is fine. On Windows the dll is installed in the bin directory.

**Comment by tdegeus** [comment]
Great. For a future, you can use git to generate patches

**Comment by kordejong** [comment]
Hi @tdegeus, I am pretty sure the current available docopt.cpp Conda package cannot be used on Windows because it lacks the import library and installs the dll in the wrong location. This pull request fixes both issues. Can you please review and merge it once you have the time? Let me know if I can be of help. Once the PR is merged I will test it by building a client on Windows.

**Comment by tdegeus** [comment]
@kordejong I had reviewed ;) My question:
```
git format-patch 42ebcec9dc2c99a1b3a4542787572045763ad196 -o patches
cat patches/0004-install-dlls-in-CMAKE_INSTALL_BINDIR.patch
```
gives 
```
From d6a0987631cb770fb9f0f7aac104bdcd38283474 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Th=C3=A9o=20DELRIEU?= <theo.delrieu@tanker.io>
Date: Tue, 19 Nov 2019 15:02:45 +0100
Subject: [PATCH 4/5] install dlls in CMAKE_INSTALL_BINDIR

---
 CMakeLists.txt | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 14c3420..28da614 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -91,7 +91,10 @@ endif()
 set(export_name "docopt-targets")

 # Runtime package
-install(TARGETS docopt EXPORT ${export_name} DESTINATION ${CMAKE_INSTALL_LIBDIR})
+install(TARGETS docopt EXPORT ${export_name}
+	RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
+	ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})

 # Development package
 install(FILES ${docopt_HEADERS} DESTINATION include/docopt)
--
2.37.0 (Apple Git-136)
```

I think this is crucially different from the PR as it does not change the filename:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
```

**Comment by kordejong** [comment]
Ah, we were in a deadlock ;-)

The patch I made doesn't rename `CMakeLists.txt`, does it? The results show that the patch is applied to the original file.

To be safe I made a local patch file instead of using git diff because the docopt repository got out of sync with the version of docopt that is being used by this feedstock.

See also:

- [Applying patch](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=579627&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=76)
- [Installing import lib / dll in seperate directories](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=579627&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=450)

Nothing has changed in the non-Windows case: [still installing shared lib in lib directory](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=579627&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=209).

**Comment by tdegeus** [comment]
Thanks. Could you : 

* In `bld.bat` add on the first line `cat CMakeLists.txt`, just to make sure ?
* Comment why there is the postfix `.new` in `+++ CMakeLists.txt.new`?

**Comment by kordejong** [comment]
>     * Comment why there is the postfix `.new` in `+++ CMakeLists.txt.new`?

Here's how you locally make and use a patch file, using GNU diff and patch:
1. Copy `my_file.txt` to `my_file.txt.new`
2. Update `my_file.txt.new`
3. `diff -u my_file.txt my_file.txt.new > my_changes.patch`

Anybody with `my_file.txt` can now patch it with `patch < my_changes.patch`.

Linux build:
- [File not renamed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=585383&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=181)
- [Patch applied](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=585383&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=619)

Windows build:
- [File not renamed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=585383&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=424)
- [Patch applied](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=585383&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=563)

**Comment by tdegeus** [comment]
Thanks for clarifying ! Would you be willing to remove the verification `ls` and `cat` such that I can merge?

**Comment by tdegeus** [comment]
Thanks again!

**Pull request merged**
